# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('professionnelles', 'professionnlles.'), ('méthodologiques', 'méthodologiques'), ('sociales et personnelles', 'sociales et personnelles')], default='professionnelles', max_length=30)),
            ],
            options={
                'ordering': ('code',),
                'verbose_name': 'Compétence',
            },
        ),
        migrations.CreateModel(
            name='CompetenceTransversale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('periode', models.IntegerField()),
                ('nbre_note', models.IntegerField()),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ObjectifEvaluateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('nom', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Obj. évaluateurs',
                'ordering': ('code',),
                'verbose_name': 'Obj. évaluateur',
            },
        ),
        migrations.CreateModel(
            name='ObjectifParticulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Competence')),
                ('competences_transversales', models.ManyToManyField(to='pec.CompetenceTransversale')),
            ],
            options={
                'verbose_name_plural': 'Obj. particuliers',
                'ordering': ('code',),
                'verbose_name': 'Obj. particulier',
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Global', 'Global'), ('Gén.', 'Gén.'), ('Enf.', 'Enf.'), ('PersA', 'PersA'), ('Hand.', 'Hand.')], default='Global', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='objectifevaluateur',
            name='objectif_particulier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.ObjectifParticulier'),
        ),
        migrations.AddField(
            model_name='objectifevaluateur',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Orientation'),
        ),
        migrations.AddField(
            model_name='objectifevaluateur',
            name='taxonomie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Taxonomie'),
        ),
        migrations.AddField(
            model_name='cours',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Cursus'),
        ),
        migrations.AddField(
            model_name='cours',
            name='objectifs_evaluateurs',
            field=models.ManyToManyField(to='pec.ObjectifEvaluateur'),
        ),
        migrations.AddField(
            model_name='competence',
            name='domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Domaine'),
        ),
        migrations.AlterUniqueTogether(
            name='objectifevaluateur',
            unique_together=set([('code', 'orientation')]),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together=set([('cursus', 'nom')]),
        ),
    ]
