# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencetransversale',
            options={'ordering': ('nom',), 'verbose_name': 'Comp. transversale'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ('nom',), 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='cursus',
            options={'ordering': ('code',), 'verbose_name_plural': 'Cursus'},
        ),
        migrations.RenameField(
            model_name='domaine',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='taxonomie',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='type',
        ),
        migrations.AddField(
            model_name='competence',
            name='descr',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
