# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0002_auto_20170531_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifparticulier',
            name='competence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pec.Competence'),
        ),
    ]
