# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0003_auto_20170531_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifparticulier',
            name='competences_transversales',
            field=models.ManyToManyField(blank=True, to='pec.CompetenceTransversale'),
        ),
        migrations.AlterField(
            model_name='objectifparticulier',
            name='nom',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
