# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0004_auto_20170531_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencetransversale',
            options={'ordering': ('id',), 'verbose_name': 'Comp. transversale'},
        ),
        migrations.AddField(
            model_name='objectifevaluateur',
            name='tri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectifparticulier',
            name='tri',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='objectifevaluateur',
            unique_together=set([('id', 'orientation')]),
        ),
    ]
