# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0005_auto_20170531_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='objectifevaluateur',
            options={'ordering': ('tri', 'orientation__id'), 'verbose_name': 'Obj. évaluateur', 'verbose_name_plural': 'Obj. évaluateurs'},
        ),
        migrations.AlterModelOptions(
            name='objectifparticulier',
            options={'ordering': ('tri',), 'verbose_name': 'Obj. particulier', 'verbose_name_plural': 'Obj. particuliers'},
        ),
        migrations.AddField(
            model_name='competencetransversale',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pec.TypeCompetence'),
        ),
    ]
