# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0009_cours_careum'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
