# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0011_cours_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='abrev',
            field=models.CharField(blank=True, max_length=10, verbose_name='abréviation'),
        ),
    ]
