# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0012_domaine_abrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='formation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
