# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0013_cours_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pec',
            field=models.ManyToManyField(blank=True, to='pec.Cursus'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cours',
            name='cursus',
        ),
    ]
