# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0014_auto_20170604_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='index_published',
            field=models.BooleanField(default=True),
        ),
    ]
