# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0015_cours_index_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='pec',
            new_name='cursus',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='formation',
        ),
    ]
