# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0017_auto_20170607_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='doc/')),
                ('titre', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='objectifs',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='sequence',
        ),
        migrations.AddField(
            model_name='sequence',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='objectifs',
            field=models.ManyToManyField(blank=True, to='pec.ObjectifEvaluateur'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='periode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lecon',
        ),
    ]
