# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0019_auto_20170609_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='cours_txt',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='careum',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
