# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0020_auto_20170609_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cursus_txt',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
