# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0021_cours_cursus_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='cours_txt',
            new_name='objectifs_evaluateurs_txt',
        ),
    ]
