# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0023_auto_20170619_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectifevaluateur',
            options={'ordering': ('tri',), 'verbose_name': 'Obj. évaluateur', 'verbose_name_plural': 'Obj. évaluateurs'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='cursus_txt',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='objectifs_evaluateurs_txt',
        ),
    ]
